[package]
name = "raystack"
version = "0.5.0"
authors = ["a-mackay <amackayfoss@outlook.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/a-mackay/raystack"
description = "WIP SkySpark client"
keywords = ["skyspark", "haystack"]


[dependencies]
base64 = "0.10.1"
chrono = "0.4.7"
chrono-tz = "0.5.1"
csv = "1.1.1"
rand = "0.7.0"
reqwest = { git = "https://github.com/seanmonstar/reqwest", rev = "0a87d3d7dacecee7648b0841e2d7716976db6115" }
rust-crypto = "0.2.36"
serde_json = "1.0.40"
url = "2.1.0"


[dev-dependencies]
tokio = { version = "=0.2.0-alpha.4" }