[package]
name = "raystack"
version = "0.7.0"
authors = ["a-mackay <amackayfoss@outlook.com>"]
license = "MIT"
edition = "2018"
repository = "https://github.com/a-mackay/raystack"
description = "WIP SkySpark client"
keywords = ["skyspark", "haystack"]


[features]
grid_csv = ["csv"]
default = ["default-tls"]
default-tls = ["reqwest/default-tls"]
rustls = ["reqwest/rustls-tls"]


[dependencies]
base64 = "0.12"
chrono = "0.4"
chrono-tz = "0.5"
csv = { version = "1.1", optional = true }
raystack_core = "0.1"
reqwest = { version = "0.10", default-features = false, features = ["json"] }
ring = "0.16.12"
serde_json = "1.0"
thiserror = "1.0"
url = "2.1"


[dev-dependencies]
tokio = { version = "0.2.0", features = ["macros"] }
