[package]
name = "raystack"
version = "0.1.0"
authors = ["a-mackay <amackayfoss@outlook.com>"]
edition = "2018"

[dependencies]
base64 = "0.10.1"
chrono = "0.4.7"
chrono-tz = "0.5.1"
rand = "0.7.0"
reqwest = "0.9.20"
rust-crypto = "0.2.36"
serde_json = "1.0.40"
url = "1.7.2"