name: build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    - name: Run Unit Tests
      run: cargo test --lib --verbose
      env:
        RAYSTACK_SKYSPARK_PROJECT_API_URL: ${{ secrets.RAYSTACK_SKYSPARK_PROJECT_API_URL }}
        RAYSTACK_SKYSPARK_USERNAME: ${{ secrets.RAYSTACK_SKYSPARK_USERNAME }}
        RAYSTACK_SKYSPARK_PASSWORD: ${{ secrets.RAYSTACK_SKYSPARK_PASSWORD }}
    - name: Run Doc Tests
      run: cargo test --doc --verbose